<?php

/**
 * PluginsfOauthServerAccessTokenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfOauthServerAccessTokenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfOauthServerAccessTokenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfOauthServerAccessToken');
    }
    
}
