<?php

/**
 * PluginsfOauthServerRequestTokenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfOauthServerRequestTokenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfOauthServerRequestTokenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfOauthServerRequestToken');
    }
}