<?php

/**
 * PluginsfOauthServerConsumer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsfOauthServerConsumer extends BasesfOauthServerConsumer
{
	  	//Surcharges pour générer la clé publique et privée
	public function save(Doctrine_Connection $conn = null)
	{
		if ($this->getConsumerKey()=="")
			$this->setConsumerKey(sfOAuthServer::generateConsumerKey($this->getName()));
		if ($this->getConsumerSecret()=="")
			$this->setConsumerSecret(sfOAuthServer::generateConsumerSecret($this->getName()));
			
		$ret = parent::save($conn);
		return $ret;
	}
	
}
