<?php

/**
 * PluginsfOauthServerConsumerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfOauthServerConsumerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfOauthServerConsumerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfOauthServerConsumer');
    }
}